<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonBack</name>
   <tag></tag>
   <elementGuidId>576fb0a7-0c25-41cc-aec6-2ae6577488a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@data-message='adb-breakcrumb-backlink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@data-message='adb-breakcrumb-backlink']</value>
   </webElementProperties>
</WebElementEntity>
