<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonFilterAndSortierung</name>
   <tag></tag>
   <elementGuidId>b67007a7-a82a-4e2d-bec4-005d19e2663f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='navigation-facet-toggle']//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='navigation-facet-toggle']//span</value>
   </webElementProperties>
</WebElementEntity>
