<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonMehrProdukteAnzeigen</name>
   <tag></tag>
   <elementGuidId>38f782b3-63d5-45c9-b764-190e748032fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-message='adb-show-more-products-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@data-message='adb-show-more-products-button']</value>
   </webElementProperties>
</WebElementEntity>
