<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LabelofProductOverviewPage</name>
   <tag></tag>
   <elementGuidId>bbb09a78-6c9b-4f5a-987e-1401085387cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='content-wrapper']//h1[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='content-wrapper']//h1[1]</value>
   </webElementProperties>
</WebElementEntity>
