<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NumberOfCurrentProductCount</name>
   <tag></tag>
   <elementGuidId>c072350a-5686-4719-b5fe-1dd1359e026f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[@class='pagination-show-more__result']//span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[@class='pagination-show-more__result']//span[1]</value>
   </webElementProperties>
</WebElementEntity>
