<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SalesUnitProductListTile</name>
   <tag></tag>
   <elementGuidId>c51ab6d0-d841-46ee-8c7f-448c8c1c784f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='price-tag__sales-unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='price-tag__sales-unit']</value>
   </webElementProperties>
</WebElementEntity>
